# Config for Dependabot updates. See Documentation here:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: 'github-actions'
    directory: '/'
    # Check for updates on a daily basis
    schedule:
      interval: 'daily'

  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for a `package.json` in the root directory
    directory: '/'
    # Check for updates on a daily basis
    schedule:
      interval: 'daily'
    # Allow both patch and minor updates, but require manual PR approval for major versions
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'npm'

  # Enable version updates for Docker
  # We need to specify each Dockerfile in a separate entry because Dependabot doesn't
  # support wildcards or recursively checking subdirectories. Check this issue for updates:
  # https://github.com/dependabot/dependabot-core/issues/2178
  - package-ecosystem: 'docker'
    directory: 'compose/local/'
    schedule:
      interval: 'daily'
    # Ignore minor version updates but update patch versions automatically
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'
    labels:
      - 'dependencies'
      - 'docker'

  - package-ecosystem: 'docker'
    directory: 'compose/production/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'
    labels:
      - 'dependencies'
      - 'docker'

  - package-ecosystem: 'docker'
    directory: 'compose/production/nginx/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'
    labels:
      - 'dependencies'
      - 'docker'

  - package-ecosystem: 'docker'
    directory: 'compose/staging/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'
    labels:
      - 'dependencies'
      - 'docker'

  - package-ecosystem: 'docker'
    directory: 'compose/staging/nginx/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'
    labels:
      - 'dependencies'
      - 'docker'