services:

  nextjs:
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    environment:
      - NEXT_PUBLIC_SENTRY_DSN=${SENTRY_DSN}
      - NODE_ENV=production
    expose:
      - 3000
